DB_NAME = "taxi_pipeline"
DB_USER = "neondb_owner"
DB_PASSWORD = "npg_moJ6pPaS9VQq"
DB_HOST = "ep-noisy-queen-apk02egr-pooler.c-7.us-east-1.aws.neon.tech"
DB_PORT = "5432"
OPENAI_API_KEY = "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"